### ISSUE TITLE
Failed to call API with Statistics API

### ISSUE THREAD

**Issue by duylamvo** [criteo/criteo-python-marketing-sdk#1]
My code: 
```
api_instance = criteo_marketing.AuthenticationApi()
api_response = api_instance.o_auth2_token_post(client_id=client_id, client_secret=client_secret, grant_type=grant_type)
authorization = "Bearer {}".format(api_response.access_token)
api_instance = criteo_marketing.StatisticsApi()
stats_query_message_ex = criteo_marketing.StatsQueryMessageEx(
        report_type="CampaignPerformance"
        , dimensions=["CampaignId"]
        , metrics=["Clicks"]
        , start_date="2019-01-01"
        , end_date="2019-01-09"
        , format="Csv")
api_instance.get_stats(authorization , stats_query_message_ex)
**in _refresh_token
    raise ValueError('client_id (username) is missing')
ValueError: client_id (username) is missing**
```

Failed to call because of client_id, I guess the check in default get from configuration not from parsed headers (where client_id stored)

**Comment by duylamvo** [comment]
try with call api from web by copying authorization to the https://api.criteo.com/marketing/swagger/ui/index#!/Statistics/Statistics_GetStats

It is successful.

**Comment by tpeyrard** [comment]
Hello @dungthuapps, thanks for reporting your issue.

In fact you got the error because you didn't provide the Configuration object to the ApiClient. These are optional, that's why you didn't have to configure them. Hence, you shouldn't get the error => I'll provide a fix.

Meanwhile, to overcome this problem and get the "automatic token refresh" feature, you can follow the example: https://github.com/criteo/criteo-python-marketing-sdk/blob/f28a3e5a54966c4818c00a8abf99992cbdc8a1a7/examples/authentication.py#L17-L25.

**Comment by duylamvo** [comment]
Hi @tpeyrard, 
It is good to use configuration. I dont see error. 
But when try with get_stats, the result is none. When trying with [https://api.criteo.com/marketing/swagger/ui/index#!/Statistics/Statistics_GetStats](swagger) , result is a link of csv file

**Comment by duylamvo** [comment]
my code: 
```
api_instance = criteo_marketing.StatisticsApi(client)
stats_query_message_ex = criteo_marketing.StatsQueryMessageEx(
            report_type="CampaignPerformance"
            , dimensions=["CampaignId"]
            , metrics=["Clicks"]
            , start_date="2019-01-01"
            , end_date="2019-01-09"
            , format="Csv")
stats_response = api_instance.get_stats(token, stats_query_message_ex)
pprint(stats_response)
```
result: None

**Comment by duylamvo** [comment]
when using debug, I found the data was returned. but dont know how to get this data

```
DEBUG:urllib3.connectionpool:https://api.criteo.com:443 "POST /marketing/v1/statistics HTTP/1.1" 200 136
DEBUG:criteo_marketing.rest:response body: 
﻿Advertiser Name;Campaign ID;Campaign Name;Currency;Clicks
Adviser_1;222;abc;EUR;111
Adviser_1;222;abc;EUR;111
```

**Comment by duylamvo** [comment]
Turn out, it sets response_type = None, (even with response_data != None) 
(in statistics_api.py, method get_stats_with_http_info(.)
`        return self.api_client.call_api(
            '/v1/statistics', 'POST',
...
            response_type=None,  # noqa: E501
...)`

**Comment by tpeyrard** [comment]
Hello,
I'll have a look why this endpoints forces OpenAPI generator to set the `response_type` to `None`.

**Comment by tpeyrard** [comment]
Hi @dungthuapps,

patch is on its way. I hope to deploy it today or next Monday.

**Comment by tpeyrard** [comment]
Hi @dungthuapps,

patch is on its way. I hope to deploy it today or next Monday.

**Comment by tpeyrard** [comment]
@dungthuapps, changes have been rollout.

Please tell me if it works on your side. I added an example to save the content to a file: https://github.com/criteo/criteo-python-marketing-sdk/blob/9bddf47341ef88c9f93566775ce39499a2450a5c/examples/statistics.py#L25-L45

**Comment by duylamvo** [comment]
hi, updated new version. it works from my side. 
both the code above and get_stats(.)

thanks

**Comment by negm** [comment]
Hello 
what is the metric name to get the spend of the campaign. I tried cost,spend, campaignCost to no avail. The swagger documentation also doesn't have a place that lists the available metrics to query

**Comment by rmadisonhaynie** [comment]
> Hello
> what is the metric name to get the spend of the campaign. I tried cost,spend, campaignCost to no avail. The swagger documentation also doesn't have a place that lists the available metrics to query

Hello @negm could you please ask your question in a new issue, thank you.
